name: ollama-firecrawl

include:
  - ./firecrawl/docker-compose.yaml
  - ./hermes-agent/docker-compose.windows.yml

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks:
    - backend
  restart: unless-stopped
  ports:
    - "11434:11434"
  volumes:
    - ollama_storage:/root/.ollama
  environment:
    - OLLAMA_KEEP_ALIVE=24H
    - OLLAMA_CONTEXT_LENGTH=64000
  healthcheck:
    test: ["CMD", "ollama", "list"]
    interval: 10s
    timeout: 5s
    retries: 10

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  container_name: ollama-pull-llama
  networks:
    - backend
  volumes:
    - ollama_storage:/root/.ollama
  environment:
    - OLLAMA_HOST=ollama:11434
    - OLLAMA_CONTEXT_LENGTH=64000

  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 10; ollama pull qwen3.5:4b; ollama pull llama3.2:3b; ollama pull nomic-embed-text; ollama pull qwen3:4b; ollama pull qwen3:1.7b; ollama pull gemma4:12b"

services:
  ollama:
    <<: *service-ollama
    gpus: all

  ollama-init:
    <<: *init-ollama
    gpus: all
    depends_on:
      ollama:
        condition: service_healthy
      

  

  api:
    environment:
      MODEL_NAME: ${MODEL_NAME:-qwen3.5:4b}
      MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME:-nomic-embed-text}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
volumes:
  ollama_storage:

